const arrayOfTracks = [
  {
    id: "1",
    name: "Track 1",
    artist: "Artist 1",
    album: "Album 1",
    url: "https://example.com/track1",
  },
  {
    id: "2",
    name: "Track 2",
    artist: "Artist 2",
    album: "Album 2",
    url: "https://example.com/track2",
  },
  {
    id: "3",
    name: "Track 3",
    artist: "Artist 3",
    album: "Album 3",
    url: "https://example.com/track3",
  },
  {
    id: "4",
    name: "Track 4",
    artist: "Artist 4",
    album: "Album 4",
    url: "https://example.com/track4",
  },
  {
    id: "5",
    name: "Track 5",
    artist: "Artist 5",
    album: "Album 5",
    url: "https://example.com/track5",
  },
  {
    id: "6",
    name: "Track 6",
    artist: "Artist 6",
    album: "Album 6",
    url: "https://example.com/track6",
  },
  {
    id: "7",
    name: "Track 7",
    artist: "Artist 7",
    album: "Album 7",
    url: "https://example.com/track7",
  },
  {
    id: "8",
    name: "Track 8",
    artist: "Artist 8",
    album: "Album 8",
    url: "https://example.com/track8",
  },
  {
    id: "9",
    name: "Track 9",
    artist: "Artist 9",
    album: "Album 9",
    url: "https://example.com/track9",
  },
  {
    id: "10",
    name: "Track 10",
    artist: "Artist 10",
    album: "Album 10",
    url: "https://example.com/track10",
  },
  {
    id: "11",
    name: "Track 11",
    artist: "Artist 11",
    album: "Album 11",
    url: "https://example.com/track11",
  },
  {
    id: "12",
    name: "Track 12",
    artist: "Artist 12",
    album: "Album 12",
    url: "https://example.com/track12",
  },
  {
    id: "13",
    name: "Track 13",
    artist: "Artist 13",
    album: "Album 13",
    url: "https://example.com/track13",
  },
  {
    id: "14",
    name: "Track 14",
    artist: "Artist 14",
    album: "Album 14",
    url: "https://example.com/track14",
  },
  {
    id: "15",
    name: "Track 15",
    artist: "Artist 15",
    album: "Album 15",
    url: "https://example.com/track4",
  },
  {
    id: "16",
    name: "Track 16",
    artist: "Artist 16",
    album: "Album 16",
    url: "https://example.com/track16",
  },
  {
    id: "17",
    name: "Track 17",
    artist: "Artist 17",
    album: "Album 17",
    url: "https://example.com/track17",
  },
  {
    id: "18",
    name: "Track 18",
    artist: "Artist 18",
    album: "Album 18",
    url: "https://example.com/track18",
  },
  {
    id: "19",
    name: "Track 19",
    artist: "Artist 19",
    album: "Album 19",
    url: "https://example.com/track19",
  },
  {
    id: "20",
    name: "Track 20",
    artist: "Artist 20",
    album: "Album 20",
    url: "https://example.com/track20",
  },
  {
    id: "21",
    name: "Track 21",
    artist: "Artist 21",
    album: "Album 21",
    url: "https://example.com/track21",
  },
  {
    id: "22",
    name: "Track 22",
    artist: "Artist 22",
    album: "Album 22",
    url: "https://example.com/track22",
  },
  {
    id: "21",
    name: "Track 21",
    artist: "Artist 21",
    album: "Album 21",
    url: "https://example.com/track21",
  },
  {
    id: "22",
    name: "Track 22",
    artist: "Artist 22",
    album: "Album 22",
    url: "https://example.com/track22",
  },
  {
    id: "23",
    name: "Track 23",
    artist: "Artist 23",
    album: "Album 23",
    url: "https://example.com/track23",
  },
  {
    id: "24",
    name: "Track 24",
    artist: "Artist 24",
    album: "Album 24",
    url: "https://example.com/track24",
  },
  {
    id: "25",
    name: "Track 25",
    artist: "Artist 25",
    album: "Album 25",
    url: "https://example.com/track25",
  },
  {
    id: "26",
    name: "Track 26",
    artist: "Artist 26",
    album: "Album 26",
    url: "https://example.com/track26",
  },
  {
    id: "27",
    name: "Track 27",
    artist: "Artist 27",
    album: "Album 27",
    url: "https://example.com/track27",
  },
  {
    id: "28",
    name: "Track 28",
    artist: "Artist 28",
    album: "Album 28",
    url: "https://example.com/track28",
  },
  {
    id: "29",
    name: "Track 29",
    artist: "Artist 29",
    album: "Album 29",
    url: "https://example.com/track29",
  },
  {
    id: "30",
    name: "Track 30",
    artist: "Artist 30",
    album: "Album 30",
    url: "https://example.com/track30",
  },
];

function onSearch(query) {
  return arrayOfTracks.map(track => track);
}

export default onSearch;

